#pragma once

#include <cstdio>
#include <string>

#include <discord-rpc.hpp>
#include <hl.h>
#include "hl-idl-helpers.hpp"

// pref<T> is defined in the generated idl_hl.cpp — forward-declare so we can
// use pref<discord::User>* in callback signatures without a full definition.
template<typename T> struct pref;

// HL callback function pointer types (match the casts generated by hl-idl)
using HL_UserCB   = void(*)(pref<discord::User>*);
using HL_StrCB    = void(*)(vstring*);
using HL_IntStrCB = void(*)(int, vstring*);

// hl-idl generates valueToIndex1(int), but discord uses enum class which
// doesn't implicitly convert to int — these wrappers bridge that gap.
inline int Presence_getPartyPrivacy(discord::Presence* p) {
	return (int)p->getPartyPrivacy();
}
inline int Presence_getActivityType(discord::Presence* p) {
	return (int)p->getActivityType();
}
inline int Presence_getStatusDisplayType(discord::Presence* p) {
	return (int)p->getStatusDisplayType();
}

// std::optional<std::string> getters for discord::User
inline vstring* hl_utf8_to_hlstr_opt(std::optional<std::string> str) {
	return str.has_value() ? hl_utf8_to_hlstr(str->c_str()) : nullptr;
}

// setButton1/2(Button): hl-idl passes Button* but discord expects Button const&
inline discord::Presence& Presence_setButton1(discord::Presence* p, discord::Presence::Button* b) {
	return p->setButton1(*b);
}
inline discord::Presence& Presence_setButton2(discord::Presence* p, discord::Presence::Button* b) {
	return p->setButton2(*b);
}

// setPresence: hl-idl passes Presence* but discord expects Presence const&
inline discord::RPCManager& RpcManager_setPresence(discord::RPCManager* m, discord::Presence* p) {
	return m->setPresence(*p);
}

discord::RPCManager& RpcManager_pumpEvents(discord::RPCManager* m);

discord::RPCManager& RpcManager_onReady(discord::RPCManager* m, HL_UserCB cb);
discord::RPCManager& RpcManager_onDisconnected(discord::RPCManager* m, HL_IntStrCB cb);
discord::RPCManager& RpcManager_onErrored(discord::RPCManager* m, HL_IntStrCB cb);
discord::RPCManager& RpcManager_onJoinGame(discord::RPCManager* m, HL_StrCB cb);
discord::RPCManager& RpcManager_onSpectateGame(discord::RPCManager* m, HL_StrCB cb);
discord::RPCManager& RpcManager_onJoinRequest(discord::RPCManager* m, HL_UserCB cb);